FREEIPA_USERNAME = ""
FREEIPA_PASSWORD = ""

SMTP_PASSWORD = ""
SMTP_USER = ""
SMTP_HOST = ""

SMTP_PORT = 0

module.exports = {FREEIPA_USERNAME, FREEIPA_PASSWORD, SMTP_PASSWORD, SMTP_USER, SMTP_HOST, SMTP_PORT}